### ISSUE TITLE
The Units classes are mis-namespaced

### ISSUE THREAD

**Issue by tolnem** [rugaard/dmi#1]
Hi!

Thanks for writing this library, it is very helpful for my little hobby project. However, I could only get it working once I corrected the namespace for all the Units classes, which according to the code are inside DTO, but in the directory structure are not.

So either the Units classes should be moved inside DTO (again?), or the code that references them, and their own namespace declarations, should be changed.

Kind regards,
David

**Comment by rugaard** [comment]
Thank you for reporting this @tolnem. I'll get right on it 🙂

**Comment by rugaard** [comment]
@tolnem Just released `1.1.8` which should fix the namespace issue. Thanks again for reporting it 🙏🏻
